// src/styles/commonStyles.js - Complete StyleSheet
import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  screenContainer: {
    flex: 1,
    backgroundColor: '#F5F7FA',
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 40,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoIcon: {
    fontSize: 24,
    marginRight: 8,
  },
  logoText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  languageBtn: {
    padding: 8,
  },
  languageText: {
    fontSize: 16,
  },
  contentCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2C3E50',
    textAlign: 'center',
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  locationIcon: {
    fontSize: 60,
    marginVertical: 20,
  },
  infoBox: {
    backgroundColor: '#FFF',
    padding: 15,
    borderRadius: 12,
    marginTop: 20,
    minWidth: 200,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  infoLabel: {
    color: '#7F8C8D',
    fontSize: 14,
  },
  infoValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginTop: 5,
  },
  bottomSection: {
    paddingBottom: 20,
  },
  primaryButton: {
    backgroundColor: '#4A90E2',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 10,
  },
  primaryButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  linkText: {
    color: '#4A90E2',
    textAlign: 'center',
    fontSize: 14,
  },
  screenTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 5,
  },
  screenSubtitle: {
    fontSize: 14,
    color: '#7F8C8D',
    marginBottom: 30,
  },
  formContainer: {
    flex: 1,
  },
  inputLabel: {
    fontSize: 16,
    color: '#2C3E50',
    marginBottom: 10,
    fontWeight: '600',
  },
  inputButton: {
    backgroundColor: '#4A90E2',
    padding: 16,
    borderRadius: 12,
    marginBottom: 10,
  },
  inputButtonText: {
    color: '#FFF',
    fontSize: 16,
  },
  inputButtonOutline: {
    backgroundColor: '#FFF',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  inputButtonOutlineText: {
    color: '#2C3E50',
    fontSize: 16,
  },
  ageButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  ageButton: {
    flex: 1,
    backgroundColor: '#FFF',
    padding: 12,
    borderRadius: 12,
    marginHorizontal: 5,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  ageButtonActive: {
    backgroundColor: '#4A90E2',
    borderColor: '#4A90E2',
  },
  ageButtonText: {
    color: '#2C3E50',
    fontSize: 14,
  },
  ageButtonTextActive: {
    color: '#FFF',
  },
  workTypeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  workTypeCard: {
    width: '48%',
    aspectRatio: 1,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  workTypeCardActive: {
    borderWidth: 3,
    borderColor: '#2C3E50',
  },
  workTypeIcon: {
    fontSize: 40,
    marginBottom: 10,
  },
  workTypeLabel: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  bottomButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  skipButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#FFF',
    marginRight: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  skipButtonText: {
    color: '#7F8C8D',
    fontSize: 16,
  },
  finishButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#5CB85C',
    alignItems: 'center',
  },
  finishButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  locationDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    padding: 15,
    borderRadius: 12,
    marginBottom: 30,
  },
  locationText: {
    marginLeft: 10,
    fontSize: 16,
    color: '#2C3E50',
  },
  otpContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  otpInput: {
    width: 45,
    height: 50,
    backgroundColor: '#FFF',
    borderRadius: 12,
    textAlign: 'center',
    fontSize: 20,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  otpCheckButton: {
    width: 50,
    height: 50,
    backgroundColor: '#5CB85C',
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpCheckText: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: 'bold',
  },
  otpHelperText: {
    textAlign: 'center',
    color: '#7F8C8D',
    fontSize: 14,
    marginBottom: 30,
  },
  homeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  greeting: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  subGreeting: {
    fontSize: 14,
    color: '#7F8C8D',
    marginTop: 5,
  },
  menuIcon: {
    fontSize: 28,
    color: '#2C3E50',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  searchInput: {
    flex: 1,
    padding: 12,
    fontSize: 16,
  },
  searchIcon: {
    fontSize: 20,
    color: '#4A90E2',
  },
  tabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 10,
    marginBottom: 20,
  },
  tab: {
    alignItems: 'center',
    padding: 10,
  },
  tabIcon: {
    fontSize: 24,
    marginBottom: 5,
  },
  tabText: {
    fontSize: 12,
    color: '#2C3E50',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 15,
    marginTop: 10,
  },
  subTitle: {
    fontSize: 14,
    color: '#7F8C8D',
    marginBottom: 15,
  },
  jobCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  jobCardLeft: {
    flex: 1,
  },
  jobCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  jobTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  jobBadge: {
    backgroundColor: '#FFE5E5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  jobBadgeText: {
    color: '#FF6B6B',
    fontSize: 12,
    fontWeight: 'bold',
  },
  jobLocation: {
    fontSize: 14,
    color: '#7F8C8D',
    marginBottom: 5,
  },
  jobSkills: {
    fontSize: 13,
    color: '#7F8C8D',
    marginBottom: 3,
  },
  jobPayment: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#5CB85C',
    marginTop: 5,
  },
  jobDuration: {
    fontSize: 13,
    color: '#7F8C8D',
    marginTop: 3,
  },
  jobCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
  },
  jobTiming: {
    fontSize: 13,
    color: '#7F8C8D',
  },
  acceptButton: {
    backgroundColor: '#5CB85C',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginTop: 10,
  },
  acceptButtonSmall: {
    backgroundColor: '#5CB85C',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 8,
  },
  acceptButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  statusBadge: {
    backgroundColor: '#FFF',
    padding: 10,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginBottom: 15,
  },
  statusText: {
    color: '#2C3E50',
    fontWeight: 'bold',
  },
  mapPlaceholder: {
    backgroundColor: '#E8F4F8',
    height: 150,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    flexDirection: 'row',
  },
  mapIcon: {
    fontSize: 40,
    marginHorizontal: 20,
  },
  paginationDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E0E0E0',
    marginHorizontal: 4,
  },
  dotActive: {
    backgroundColor: '#4A90E2',
    width: 24,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 30,
    paddingHorizontal: 20,
  },
  ratingItem: {
    alignItems: 'center',
  },
  ratingCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E0E0E0',
    marginBottom: 8,
  },
  ratingCircleActive: {
    backgroundColor: '#5CB85C',
  },
  ratingLabel: {
    fontSize: 12,
    color: '#7F8C8D',
    textAlign: 'center',
  },
  ratingLine: {
    flex: 1,
    height: 2,
    backgroundColor: '#E0E0E0',
    marginHorizontal: -10,
  },
  tabRow: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  tabItem: {
    flex: 1,
    padding: 12,
    alignItems: 'center',
    backgroundColor: '#FFF',
    marginHorizontal: 5,
    borderRadius: 8,
  },
  tabItemActive: {
    flex: 1,
    padding: 12,
    alignItems: 'center',
    backgroundColor: '#4A90E2',
    marginHorizontal: 5,
    borderRadius: 8,
  },
  tabItemText: {
    color: '#7F8C8D',
    fontSize: 14,
  },
  tabItemActiveText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  activeJobCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  activeJobHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  activeJobTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2C3E50',
  },
  activeJobStatus: {
    fontSize: 14,
    color: '#FF9800',
  },
  activeJobLocation: {
    fontSize: 14,
    color: '#7F8C8D',
    marginBottom: 10,
  },
  activeJobDetails: {
    marginBottom: 10,
  },
  activeJobPayment: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#5CB85C',
  },
  illustrationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 30,
  },
  illustrationIcon: {
    fontSize: 60,
    marginHorizontal: 20,
  },
  linkButton: {
    alignItems: 'center',
    padding: 15,
  },
  linkButtonText: {
    color: '#4A90E2',
    fontSize: 14,
  },
  detailCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
  },
  detailLabel: {
    fontSize: 14,
    color: '#2C3E50',
    marginBottom: 8,
  },
  ratingStars: {
    marginTop: 5,
  },
  workerCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    flexDirection: 'row',
    alignItems: 'center',
  },
  workerAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#E8F4F8',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  avatarText: {
    fontSize: 24,
  },
  workerInfo: {
    flex: 1,
  },
  workerName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2C3E50',
    marginBottom: 3,
  },
  workerRole: {
    fontSize: 14,
    color: '#7F8C8D',
    marginBottom: 3,
  },
  workerExp: {
    fontSize: 13,
    color: '#7F8C8D',
  },
  ratingBadge: {
    backgroundColor: '#FFF9E6',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FFD700',
  },
  shortlistButton: {
    backgroundColor: '#4A90E2',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
  },
  shortlistButtonText: {
    color: '#FFF',
    fontWeight: 'bold',
  },
});

export default styles;
